# Site settings
title: SciViews
email: phgrosjean@sciviews.org
description: > # this means to ignore newlines until "baseurl:"
  SciViews is a layer on top of the software R (http://www.r-project.org)
  to enhance its language and environment.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.sciviews.org" # the base hostname & protocol for your site
twitter_username: PhilGrosjean
github_username:  phgrosjean

# Build settings
markdown: kramdown
